"""Apply optional human-reviewed raw-label mappings.

The paper-level fields data_type_taxonomy_categories and algorithm_taxonomy_categories were
already verified by Claude + Gemini and, when needed, human adjudication. Those reviewed fields
remain authoritative and are NOT regenerated by a new GPT-only taxonomy-mapping call.
"""

import csv
from common import OUTPUT_DIR, read_jsonl, write_jsonl, write_csv, normalize_list

INPUT_JSONL = OUTPUT_DIR / "05_adjudicated_extractions.jsonl"
DATA_TYPES_MAP_CSV = OUTPUT_DIR / "05_data_type_mapping_for_review.csv"
ALGORITHMS_MAP_CSV = OUTPUT_DIR / "05_algorithm_mapping_for_review.csv"
OUTPUT_JSONL = OUTPUT_DIR / "06_final_mapped_extractions.jsonl"
OUTPUT_CSV = OUTPUT_DIR / "06_final_mapped_extractions.csv"


def load_mapping(path):
    mapping = {}
    if not path.exists() or path.stat().st_size == 0:
        return mapping
    with path.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            raw = (row.get("raw_label") or "").strip()
            final = (row.get("final_standard_label") or "").strip()
            if raw and final:
                mapping[raw] = final
    return mapping


def collect_data_types(row):
    values = []
    values.extend(normalize_list(row.get("wearable_data_types_raw", [])))
    for device_row in row.get("device_extractions", []) or []:
        if isinstance(device_row, dict):
            values.extend(normalize_list(device_row.get("wearable_data_types_raw", [])))
    return values


def mapped_unique(values, mapping):
    out = []
    for value in normalize_list(values):
        mapped = mapping.get(value, value)
        if mapped and mapped not in out:
            out.append(mapped)
    return out


data_mapping = load_mapping(DATA_TYPES_MAP_CSV)
algorithm_mapping = load_mapping(ALGORITHMS_MAP_CSV)

rows = []
for row in read_jsonl(INPUT_JSONL):
    row = dict(row)

    row["data_types_standardized"] = mapped_unique(collect_data_types(row), data_mapping)
    row["algorithm_types_standardized"] = mapped_unique(
        row.get("algorithm_types_raw", []), algorithm_mapping
    )

    row["final_data_type_taxonomy_categories"] = row.get("data_type_taxonomy_categories", [])
    row["final_algorithm_taxonomy_categories"] = row.get("algorithm_taxonomy_categories", [])
    row["taxonomy_source"] = (
        "GPT primary extraction -> Claude + Gemini verification -> human adjudication if flagged"
    )
    rows.append(row)

write_jsonl(OUTPUT_JSONL, rows)
write_csv(OUTPUT_CSV, rows)
print(f"Wrote final mapped extraction files:\n{OUTPUT_JSONL}\n{OUTPUT_CSV}")
